[[redirects]]
  from = "/dev"
  to = "/dev.html"
  status = 200

[[redirects]]
  from = "/privacy-policy-assistantx"
  to = "/privacy-policy-assistantx.html"
  status = 200

[[redirects]]
  from = "/terms-of-service-assistantx"
  to = "/terms-of-service-assistantx.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
